name: Build, Test, Coverage

on: [push]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build
      run: ./gradlew build --no-daemon

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run Tests
      run: ./gradlew test --no-daemon
    - name: Upload Test Results
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: lib/build/reports/tests/test/
    - name: Generate Test Coverage Report
      run: ./gradlew jacocoTestReport --no-daemon
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        fail_ci_if_error: true
        files: ./lib/build/reports/jacoco/test/jacocoTestReport.xml
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  detekt:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Detekt
        run: ./gradlew detekt --no-daemon

      - name: Upload Detekt Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: detekt-report
          path: lib/build/reports/detekt/detekt.html

      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        if: success() || failure()
        with:
          sarif_file: lib/build/reports/detekt/detekt.sarif

